name: jvm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-tests:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ] #, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: test
          build-root-directory: ./jvm
      - uses: actions/upload-artifact@v3
        with:
          name: Test report
          path: ./build/reports/tests/test/index.html